evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /Theme/Evenement


admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /_profiler_home

sport:
    resource: "@SportBundle/Resources/config/routing.yml"
    prefix:   /sport


parc:
    resource: "@ParcBundle/Resources/config/routing.yml"
    prefix:   /parc

monument:
    resource: "@MonumentBundle/Resources/config/routing.yml"
    prefix:   /monument

Evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
